spring:
  application:
    name: eureka-server

#Tomcat Embedded Server Configuration
server:
  port: 8761

#Eureka Configuration Properties
eureka:
  renewalPercentThreshold: 85
  client:
    registerWithEureka: false
    fetchRegistry: false
