version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongoLocal
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongodb-init.js:/docker-entrypoint-initdb.d/mongo-init.js
volumes:
  mongo-data: